Reviews
YevhenPetrovskyi/group-14-photo-school pull request #16
Opened 2023-10-12 14:06 UTC by SvKost

2023-10-12 17:36 UTC, anyalenzy commented on src/css/reviews.css
> +  margin-left: 66px;
я би задала тут pading left (66) бо ним ви відштовхуєтесь від батька (від вашого айтем)...а от нижній так, марджин, бо то вже між елементами

2023-10-13 08:06 UTC, YevhenPetrovskyi requested changes

2023-10-13 08:06 UTC, YevhenPetrovskyi commented on src/css/reviews.css
> +  margin-left: 66px;
Падінги там не спацьовують нормально, тільки маржини працюють

2023-10-13 08:06 UTC, YevhenPetrovskyi commented on src/partials/reviews.html
> +            <p class="reviews-client-name">Abraham Baker</p>
краще зробити як h3 для кращої семантики

2023-10-13 08:06 UTC, YevhenPetrovskyi commented on src/partials/reviews.html
> +            <p class="reviews-client-name">Amanda Lowery</p>
краще зробити як h3 для кращої семантики

2023-10-13 08:06 UTC, YevhenPetrovskyi commented on src/css/reviews.css
> +  font-weight: 400;
прибрати, бо по замовчуванню для тегу p жирністьь 400

2023-10-13 08:06 UTC, YevhenPetrovskyi commented on src/css/reviews.css
> +    line-height: 1.25;
Забули про font-size: 16px;

2023-10-13 08:33 UTC, YevhenPetrovskyi commented on src/css/reviews.css
> +  margin-left: 66px;
Краще лишити маржин

2023-10-13 14:15 UTC, YevhenPetrovskyi approved these changes

2023-10-13 14:15 UTC, merged